version: "3"

services:
  mysql:
    image: mysql
    networks:
      - overlay
    environment:
      - MYSQL_MAJOR=8.0
      - MYSQL_VERSION=8.0.26-1debian10
      - MYSQL_DATABASE=nfc
      - GOSU_VERSION=1.12
      - MYSQL_ROOT_PASSWORD
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - database-volume:/var/lib/mysql
  dal-backend:
    build: .
    networks:
      - overlay
    ports:
      - "8080:8080"

volumes:
  database-volume:

networks:
  - overlay
