version: "3"

services:
  nfc-database:
    image: mysql
    networks:
      - dal-network
    environment:
      - MYSQL_MAJOR=8.0
      - MYSQL_VERSION=8.0.26-1debian10
      - MYSQL_DATABASE=nfc
      - GOSU_VERSION=1.12
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - MYSQL_ROOT_PASSWORD
    volumes:
      - database-volume:/var/lib/mysql
  nfc-dal-backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - NFC_USER_PASSWORD
    networks:
      - dal-network
    ports:
      - "8080:80"

volumes:
  database-volume:

networks:
  dal-network:
